/**:
  ros__parameters:
    random_walk_timer_period: 0.2
    random_walk_linear: 0.15
    random_walk_angular: 5.0
    random_walk_rot_interval: 2.0
    random_walk_lin_interval_min: 2.5
    random_walk_lin_interval_max: 4.5